const messages = {
  userCreated: 'Account created successfully',
  invalidName: 'Please provide a valid names',
  invalidEmailValue: 'Please provide a valid email',
  invalidPhoneNumberValue: 'Please provide a valid phoneNumber',
  invalidPasswordValue: 'Please provide a valid password',
  duplicateUserAccount: 'This account already exist',
  successfulLogin: 'LoggedIn successfully',
  userNotFound: 'No account associated to this credentials',
  incorrectPassword: 'Incorrect password',
  postItem: 'Item posted successfully',
  unauthorizedAccess: 'Unauthorized access',
  invalidToken: 'Invalid token',
  invalidname: 'Please provide a valid name',
  invalidQuantity: 'Please provide a valid item Qunatnity',
  itemDuplication: 'You can not create the same project twice',
  allItems: 'all items',
  itemDetails: 'Item details',
  invalidId: 'Please provide a valid id',
  itemNotFound: 'Item not Found',
  itemUpdated: 'Item updated',
  itemDeleted: 'Item deleted successfully',
  profileData: 'Profile Data',
  notEligible: 'You dont qualify for this item',
  userData: 'User Data',
  userISNotFound: 'User not found',
};
export default messages;
